理解numpy数组的轴

轴(axis)是数组中维的标志， 通过以下实例说明


| | 0      | 1 |2|3|4|
|---| ----------- | ----------- |---|---|---|
|0| 78    | 34       |87|25|83|
|1| 25  | 67        |97|22|13|
|2|78|43|87|45|89|

上面的表格，横轴就是排，纵轴就是列



给它加上数组下标，变成下表

| | 0      | 1 |2|3|4|
|---| ----------- | ----------- |---|---|---|
|0| 78(00)    | 34(01)       |87(02)|25(03)|83(04)|
|1| 25(10)  | 67(11)        |97(12)|22(13)|13(14)|
|2|78(20)|43(21)|87(22)|45(23)|89(24)|

用下面的实例求最大值

In [1]:
import numpy as np
a = np.array([[78, 34, 87, 25, 83], [25, 67, 97, 22, 13], [78, 43, 87, 45, 89]])
print(a.max(axis = 0))
print(a.max(axis = 1))

[78 67 97 45 89]
[87 97 89]


由上述实例可知，**axis=0就是纵轴的数据，axis=1时是横轴的数据**

下面创建一个三维数组

|     | 0 | 1 |
| :-----: | :-----: | :-----: |
| 00 | 0(000) | 1(001) |
| 01 | 2(010) | 3(011) |
| 10 | 4(100) | 5(101) |
| 11 | 6(110) | 7(111) |


In [2]:
import numpy as np
a = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(a)
print("--------------------------")
print(a.max(axis=0))
print()
print(a.max(axis=1))
print()
print(a.max(axis=2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
--------------------------
[[4 5]
 [6 7]]

[[2 3]
 [6 7]]

[[1 3]
 [5 7]]


如右图所示，上述数组以图中方式排列 

索引中靠前的为深度，其次为宽度，最后为长度。

生成的数组中，靠近原点的先进行排列


## numpy.rollaxis(arr, axis, start)
- arr: 输入数组
- axis: 要向后滚动的轴，其他的轴相对位置不会变
- start: 默认为0，表示完整的滚动，否则滚动到特定位置

实例：

In [1]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print("原数组：")
print(a)
print("----------------------")

print("(a, 2)")
print(np.rollaxis(a, 2))      # 将轴 2 滚动到轴 0（宽度到深度）
print("----------------------")

print("(a, 2, 1)")      # 将轴 0 滚动到轴 1：（宽度到高度）
print(np.rollaxis(a, 2, 1))

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
----------------------
(a, 2)
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
----------------------
(a, 2, 1)
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
