# 迭代数组
使用arange()函数创建一个 2  x 3 数组，并用nditer对它进行迭代

In [2]:
import numpy as np

In [3]:
a = np.arange(6).reshape(2, 3)
for x in np.nditer(a):
    print(x, end=', ')

0, 1, 2, 3, 4, 5, 

## 控制遍历顺序
- for x in np.nditer(a, order = 'F') : Fortran order      列序优先
- for x in np.nditer(a.T, order = 'C') : C order                行序优先

In [4]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组是")
print(a)
print()
b = a.T
print("原始数组的转置是")
print(b)
print()
c = b.copy(order = 'C')
print("以C风格排序")
print(c)
for x in np.nditer(c):
        print(x, end=', ')
print()
print()
d = b.copy(order = 'F')
print("以F风格排序")
print(d)
for x in np.nditer(d):
        print(x , end=', ')

原始数组是
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

原始数组的转置是
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

以C风格排序
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

以F风格排序
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

可以通过显式设置，来强制nditer对象使用某种顺序

In [5]:
a = np.arange(0, 60, 5).reshape(3, 4)
print("原始数组")
print(a)
print()
print("以C风格排序")
for x in np.nditer(a, order = 'C'):
    print (x, end = ', ')
print("\n")
print("以F风格排序")
for x in np.nditer(a, order = 'F'):
    print(x, end = ', ')

原始数组
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

以C风格排序
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

以F风格排序
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

## 修改数组中元素的值
nditer对象有另一个可选参数op_flags

默认情况下，nditer将待迭代遍历的数组视为只读对象，为了在遍历数组的同时，实现对数组元素值的修改，必须指定readwrite或者writeonly模式


In [6]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组是")
print(a)
print()
for x in np.nditer(a, op_flags = ['writeonly']):
        x[...] = 2 * x
print("修改后的数组为")
print(a)

原始数组是
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

修改后的数组为
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


## 使用外部循环
nditer类的构造器用于flags参数，它可以接受下列值

|参数|描述|
|:---:|:---|
|c_index|	可以跟踪 C 顺序的索引|
|f_index|	可以跟踪 Fortran 顺序的索引|
|multi_index|	每次迭代可以跟踪一种索引类型|
|external_loop|	给出的值是具有多个值的一维数组，而不是零维数组|

In [7]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组")
print(a)
print()
print("修改后的数组是")
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
    print(x, end='')

原始数组
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

修改后的数组是
[ 0 20 40][ 5 25 45][10 30 50][15 35 55]

## 广播迭代
如果两个数组是可广播的，nditer组合对象能够同时迭代它们

假设a的维度为 3 x 4， b的维度为 1 x 4， 则使用下列迭代器

In [8]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("第一个数组为")
print(a)
print()
b = np.array([1, 2, 3, 4], dtype = int)
print("第二个数组为")
print(b)
print()
print("修改后的数组为")
for x, y in np.nditer([a, b]):
    print("%d:%d" % (x, y), end = ', ')

第一个数组为
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

第二个数组为
[1 2 3 4]

修改后的数组为
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

# 数组操作
数组操作大概可以分为下面几类
- 修改数组形状
- 翻转数组
- 修改数组维度
- 连接数组
- 分割数组
- 数组元素的添加和删除

## 修改数组形状

|函数|描述|
|:---:|:---|
|reshape	|不改变数据的条件下修改形状|
|flat	|数组元素迭代器|
|flatten	|返回一份数组拷贝，对拷贝所做的修改不会影响原始数组|
|ravel	|返回展开数组|

### numpy.reshape
可以在不改变数据的情况下修改形状
```py
numpy.reshape(arr, newshape, order='C')
```
- order: 'C'按行， 'F'按列， 'A'原顺序，'K'元素在内存中出现的顺序

In [9]:
a = np.arange(8)
print(a)
print()

b = a.reshape(4, 2)
print(b)

[0 1 2 3 4 5 6 7]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### numpy.ndarray,flat
是一个数组元素迭代器

对数组中**每个元素**进行处理，可以使用flat属性

In [10]:
a = np.arange(9).reshape(3, 3)
for row in a:
    print(row)
print()    
for element in a.flat:
    print(element)

[0 1 2]
[3 4 5]
[6 7 8]

0
1
2
3
4
5
6
7
8


### numpy.ndarray.flatten
返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
```py
ndarray.flatten(order='C')
```

### numpr.ravel
展平的数组元素，顺序通常是C风格，返回的是数组视图，修改会影响原始数组
```py
numpy.ravel(a, order='C')
```

## 翻转数组

|函数|描述|
|:---:|:---|
|transpose|	对换数组的维度|
|ndarray.T|	和 self.transpose() 相同|
|rollaxis|	向后滚动指定的轴|
|swapaxes|	对换数组的两个轴|

### numpy.transpose
用于对换数组的维度
```py
numpy.transpose(arr, axes)
```
- axes为整形列表，对应维度，通常所有维度都会对换

In [11]:
a = np.arange(12).reshape(3, 4)
print(a)
print()
print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### numpy.ndarray.T
类似与numpy.transpose

In [12]:
print(a.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### numpy.rollaxis
向后滚动特定的轴到一个特定位置
```python
numpy.rollaxis(arr, axis, start)
```
- axis 向后滚动的轴，其他轴的相对位置不会改变
- start 默认为0，表示完整的滚动，否则会滚动到特定的位置

In [13]:
a = np.arange(8).reshape(2, 2, 2)
print("原数组")
print(a)
print("---------------------")

print(np.where(a == 6))
print(a[1, 1, 0])
print("----------------------")

b = np.rollaxis(a, 2, 0)  # 将轴2滚动到轴0 (宽度到深度)
print(b)
print(np.where(b == 6))
print("------------------------")

c = np.rollaxis(a, 2, 1)  # 将轴2滚动到轴1（宽度到高度）
print(c)
print(np.where(c == 6))

原数组
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
---------------------
(array([1]), array([1]), array([0]))
6
----------------------
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
(array([0]), array([1]), array([1]))
------------------------
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
(array([1]), array([0]), array([1]))


### numpy.swapaxes
详见np.rollaxis & swapaxes.ipynb

## 修改数组维度
|维度|	描述|
|:---:|:---|
|broadcast|	产生模仿广播的对象|
|broadcast_to|	将数组广播到新形状|
|expand_dims|	扩展数组的形状|
|squeeze|	从数组的形状中删除一维条目|

### numpy.broadcost
用于模仿广播的对象，返回一个对象，该对象封装了将一个数组广播到另一个数组的结果

In [14]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5 ,6])

# 对y广播x, 它具有iterator属性，基于自身组件的迭代器元组
b = np.broadcast(x, y)
r, c = b.iters

print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print("------------------------------")

print(b.shape) #shape返回广播对象的形状
print("------------------------------")

b = np.broadcast(x, y)
c = np.empty(b.shape)
print(c.shape)
print("==========")
c.flat= [u + v for (u, v) in b]
print(c)
print("=======")
print(x + y)

1 4
1 5
1 6
2 4
2 5
2 6
3 4
3 5
3 6
------------------------------
(3, 3)
------------------------------
(3, 3)
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


### numpy.broadcast_to
将数组广播到新形状。它在原始数组上只返回只读视图，它通常不连续

如果新形状不符合numpy的广播规则，则可能会抛出ValueError
```py
numpy.broadcast_to(arr, shape, subok)
```

In [15]:
a = np.arange(4).reshape(1, 4)
print(a)
print()
print(np.broadcast_to(a, (4, 4)))

[[0 1 2 3]]

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


### numpy.expand_dims
在指定位置插入新的轴来扩展数组的形状
```py
numpt.expand_dims(arr, axis)
```

In [16]:
x = np.array([[1, 2], [3, 4]])
print(x)
print()
y = np.expand_dims(x, axis=0)
print(y)
print()
print(x.shape, y.shape)
print("-----------------------------------")
y = np.expand_dims(x, axis=1)
print(y)
print()
print(x.ndim, y.ndim)
print(x.shape, y.shape)

[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]]

(2, 2) (1, 2, 2)
-----------------------------------
[[[1 2]]

 [[3 4]]]

2 3
(2, 2) (2, 1, 2)


### numpy.squeeze
从给定数组中删除一维的条目
```python
numpy.squeeze(arr, axis)
```

In [17]:
x = np.arange(9).reshape(1, 3, 3)
print(x)
print()
y = np.squeeze(x, axis=0)
print(y)
print()
print(x.shape, y.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

(1, 3, 3) (3, 3)


## 连接数组


|函数|	描述|
|:---:|:---|
|concatenate|	连接沿现有轴的数组序列|
|stack|	沿着新的轴加入一系列数组|
|hstack|	水平堆叠序列中的数组（列方向）|
|vstack|	竖直堆叠序列中的数组（行方向）|

### numpy.concatenate
用于沿指定轴连接形状相同的两个或多个数组
```py
nunpy.concatenate((a1, a2 ...), axis)
```
- axis很多地方都是默认为0

In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print()
print(b)
print("-----------")
print(np.concatenate((a, b), axis=0))
print()
print(np.concatenate((a, b), axis=1))
print()

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
-----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]



### numpy.stack
用于沿新轴连接数组序列
```py
numpy.stack(arrays, axis)
```

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.stack((a, b), 0))
print((np.stack((a, b), 0)).shape)
print()
print(np.stack((a, b), 1))
print((np.stack((a, b), 1)).shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


### numpy.hstack
是np.stack的变体，通过水平堆叠来生成数组

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print()
print(b)
print()
c = np.hstack((a, b))
print(c)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


### numpy.vstack
也是一种变体，通过垂直堆叠来生成数组

In [21]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 分割数组

|函数|	数组及操作|
|:---:|:---|
|split|	将一个数组分割为多个子数组|
|hsplit|	将一个数组水平分割为多个子数组（按列）|
|vsplit|	将一个数组垂直分割为多个子数组（按行）|

### numpy.split
沿特定轴将数组分割为子数组
```py
numpy.split(ary, indices_or_sections, axis)
```
- indices_or_sections: 如果是一个整数，就用该数平均分；如果是一个数组，为沿轴切分的位置（左开右闭）
- axis: 设置沿着哪个方向进行切分，默认为0，横向切分，即水平方向；为1时，纵向切分，即竖直方向

In [22]:
a = np.arange(9)
print(a)
print()
b = np.split(a, 3)
print(b)
print()
b = np.split(a, [4, 7])
print(b)

[0 1 2 3 4 5 6 7 8]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


- indices_or_sections参数为数组时，会依次切分前n个元素，不包括已经切分的元素

二维数组的情况与一维数组大致相同

In [23]:
a = np.array([[1, 2, 3],
                            [4, 5, 6], 
                            [7, 8, 9]])
print (np.split(a, [2, 3],axis = 0))
print("-----------------------")
print (np.split(a, [1, 2],axis = 1))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([], shape=(0, 3), dtype=int64)]
-----------------------
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


axis参数存在时，为0时在水平方向分割，为1时在垂直方向分割

In [24]:
a = np.arange(16).reshape(4, 4)
print(a)
print("---------------")
b = np.split(a, 2)
print(b)
print("---------------")
c = np.split(a, 2, axis=1)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
---------------
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
---------------
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


### numpy.hsplit
用于水平分割数组，通过**指定要返回的相同形状的数组数量**来拆分原数组

In [28]:
harr = np.floor(10 * np.random.random((2, 6)))
print(harr)
print()
print(np.hsplit(harr, 3))

[[0. 6. 4. 1. 0. 1.]
 [8. 1. 4. 3. 4. 1.]]

[array([[0., 6.],
       [8., 1.]]), array([[4., 1.],
       [4., 3.]]), array([[0., 1.],
       [4., 1.]])]


### numpy.vsplit
沿垂直轴分割，其余同上

In [31]:
a = np.arange(16).reshape(4, 4)
print(a)
print()
print(np.vsplit(a, 2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## 数组元素的添加与删除


|函数|	元素及描述|
|:---:|:---|
|resize|	返回指定形状的新数组|
|append|	将值添加到数组末尾|
|insert|	沿指定轴将值插入到指定下标之前|
|delete|	删掉某个轴的子数组，并返回删除后的新数组|
|unique|	查找数组内的唯一元素|

### numpy.resize
返回指定大小的新数组
如果新数组大小大于原始大小，则包含原始数组中的元素的副本
```py
numpy.resize(arr, shape)
```

In [36]:
a = np.array([[1, 2, 3],
                            [4, 5 ,6]])
print(a)
print(a.shape)
print()
b = np.resize(a, (3, 2))
print(b)
print(b.shape)
print()
b = np.resize(a, (3, 3))
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


### numpy.append
在数组的末尾添加值。追加操作会分配整个数组，并把原来的数组复制到新数组中，输入数组的维度必须匹配
```py
numpy.append(arr, values, axis=None)
```
- values的形状要和arr的相同
- axis: 默认为None。当axis无定义的时候，是横向加成，**返回总是为一维数组**

In [37]:
a = np.array([[1, 2, 3],
                            [4, 5 ,6]])
print(a)
print()
print(np.append(a, [7, 8,9]))
print()
print(np.append(a, [[7, 8 ,9]], axis = 0))
print()
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis = 1))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### numpy.insert
在给定的索引之前，沿给定轴在输入数组中插入值

```py
numpy.insert(arr, obj, values, axis)
```
- obj: 在其**之前**插入索引

In [40]:
a = np.array(([1, 2],
                            [3, 4],
                            [5, 6]))
print(a)
print("-------------")
print("未传递axis参数，输出数组会被展开")
print(np.insert(a, 3, [11, 12]))
print("--------------")
print("传递了axis参数，会广播值数组来配输入数组")
print("沿轴0广播")
print(np.insert(a, 1, 11, axis = 0))
print()
print("沿轴1广播")
print(np.insert(a, 1, 11, axis = 1))

[[1 2]
 [3 4]
 [5 6]]
-------------
未传递axis参数，输出数组会被展开
[ 1  2  3 11 12  4  5  6]
--------------
传递了axis参数，会广播值数组来配输入数组
沿轴0广播
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]

沿轴1广播
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


### numpy.delete
函数返回从输入数组中删除指定子数组的新数组

```py
numpy.delete(arr, obj, axis)
```
- obj：可以是切片、整数或者整数数组，表面要从输入数组删除的子数组
- axis：与np.insert一样，如果未提供轴参数，则输出数组将被展开

In [50]:
a = np.arange(12).reshape(3, 4)
print(a)
print("------------------")
print(np.delete(a, 5))
print("-------------------")
print(np.delete(a, 1, axis=1))
print("--------------------")
a = np.array([1, 2 ,3 ,4 ,5 ,6 ,7 ,8 , 9, 10])
print(np.delete(a, np.s_[::2]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------
[ 0  1  2  3  4  6  7  8  9 10 11]
-------------------
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
--------------------
[ 2  4  6  8 10]


### numpy.unique
用于去除数组中的重复元素
```py
numpy.unique(arr, return_index, return_inverse, return_counts)
```
- return_index：如果为True，返回新列表元素在旧列表中的位置（下标），并以列表形式储存
- return_inverse：如果为True，返回旧列表元素在新列表中的位置（下标），并以列表形式储存
- return_counts：如果为True，返回去重数组中的元素在原数组中的出现次数

In [56]:
a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])
print(a)
print("----------------------")
u = np.unique(a)
print(u)
print("----------------------")
u, indices = np.unique(a, return_index=True)
print(indices)
print("----------------------")
u,indices = np.unique(a,return_inverse=True)
print(u)
print(indices)
print("-----------------------")
print("使用下标重构元素")
print(u[indices])
print("-----------------------")
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

[5 2 6 2 7 5 6 8 2 9]
----------------------
[2 5 6 7 8 9]
----------------------
[1 0 2 4 7 9]
----------------------
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]
-----------------------
使用下标重构元素
[5 2 6 2 7 5 6 8 2 9]
-----------------------
[2 5 6 7 8 9]
[3 2 2 1 1 1]
