# 位运算
[runoob](https://www.runoob.com/numpy/numpy-binary-operators.html)


/home/kana/Desktop/Python_Test/PyQt_Learning# 字符串函数
以下函数对dtype为numpy.string_或numpy.unicode_的数组执行向量化字符串操作

这些函数在字符数组类（numpy.char）中定义

|函数|	描述|
|:---:|:---|
|add()|	对两个数组的逐个字符串元素进行**连接**|
|multiply()|	返回按元素**多重连接**后的字符串|
|center()|	**居中**字符串|
|capitalize()|	将字符串第一个字母转换为大写|
|title()|	将字符串的每个单词的第一个字母转换为大写|
|lower()|	数组元素转换为小写|
|upper()|	数组元素转换为大写|
|split()|	指定分隔符对字符串进行**分割**，并返回数组列表|
|splitlines()|	返回元素中的行列表，以换行符**分割**|
|strip()|	**移除**元素开头或者结尾处的特定字符|
|join()|	通过指定分隔符来**连接**数组中的元素|
|replace()|	使用新字符串**替换**字符串中的所有子字符串|
|decode()|	数组元素依次调用str.decode|
|encode()|	数组元素依次调用str.encode|

In [2]:
import numpy as np
print("使用add()连接两个字符串：")
print(np.char.add(['Hello, '], ['World!']))
print(np.char.add(['Hello ', 'Hi '], ['abc', 'xyz']))
print()

print("使用multiply()进行多重连接：")
print(np.char.multiply('HelloWorld', 3))
print()

print("使用center()使字符串居中：")
print(np.char.center('HelloWorld', 20, fillchar='#'))
print()

print("使用capitalize()将字符串的第一个字母转换为大写：")
print(np.char.capitalize('hello'))
print()

print("使用title()将每个单词的首字母大写：")
print(np.char.title('hello world'))
print()

print("使用lower()、upper()对所有字母大小写：")
print(np.char.lower('HELLO'))
print(np.char.upper('world'))
print()

print("使用splitlines()以换行符为分隔来分隔字符串，并返回数组：")
print("\\n，\\r，\\r\\n 都可用作换行符")
print(np.char.splitlines('I love \n the world'))
print(np.char.splitlines('I love \r the world'))

使用add()连接两个字符串：
['Hello, World!']
['Hello abc' 'Hi xyz']

使用multiply()进行多重连接：
HelloWorldHelloWorldHelloWorld

使用center()使字符串居中：
#####HelloWorld#####

使用capitalize()将字符串的第一个字母转换为大写：
Hello

使用title()将每个单词的首字母大写：
Hello World

使用lower()、upper()对所有字母大小写：
hello
WORLD

使用splitlines()以换行符为分隔来分隔字符串，并返回数组：
\n，\r，\r\n 都可用作换行符
['I love ', ' the world']
['I love ', ' the world']


In [22]:
print("strip()用于移除开头或结尾处的特定字符: ")
print(np.char.strip('Jupyter Notebook', 'Ju'))
print(np.char.strip('Jupyter  Notebok', 'ok'))
print()

print("join()通过分隔符来连接数组元素中的元素或字符串：")
print(np.char.join(' : ', 'HELLO'))
print(np.char.join([' : ', ' - '], ['google', 'brain']))
print()

print("replace()使用新字符串替换字符串中所有子字符串：")
print(np.char.replace('Hello world', 'or', 'cc'))
print()

print("encode()对数组中每个元素调用str,encode函数，默认编码是 utf-8，可以使用标准 Python 库中的编解码器")
a = np.char.encode('runoob', 'cp500') 
print (a)
print()

print("decode() 函数对编码的元素进行 str.decode() 解码")
a = np.char.encode('runoob', 'cp500') 
print (a)
print (np.char.decode(a,'cp500'))

strip()用于移除开头或结尾处的特定字符: 
pyter Notebook
Jupyter  Noteb

join()通过分隔符来连接数组元素中的元素或字符串：
H : E : L : L : O
['g : o : o : g : l : e' 'b - r - a - i - n']

replace()使用新字符串替换字符串中所有子字符串：
Hello wccld

encode()对数组中每个元素调用str,encode函数，默认编码是 utf-8，可以使用标准 Python 库中的编解码器
b'\x99\xa4\x95\x96\x96\x82'

decode() 函数对编码的元素进行 str.decode() 解码
b'\x99\xa4\x95\x96\x96\x82'
runoob


# 数学函数
NumPy包含大量的各种数学运算的函数，包括三角函数、算术运算的函数及复数处理函数等

## 三角函数
sin()、cos()和tan()

arcsin()、arccos()和arctan()

numpy.degrees() 函数可以将弧度转换为角度

In [24]:
a = np.array([0, 30, 45, 60, 90])
print(np.sin(a * np.pi / 180))
print()
print(np.cos(a * np.pi / 180))
print()
print(np.tan(a * np.pi / 180))

[0.         0.5        0.70710678 0.8660254  1.        ]

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


## 舍入函数
### numpy.around()
返回指定数字的四舍五入值
```py
numpy.around(a, decimals)
```
- decimals：舍入的小数位数，默认为0；如果为负数，整数将四舍五入到小数点左侧的位置

In [26]:
a = np.array([1.0, 5.55, 123, 0.567, 25.532])
print(np.around(a))
print (np.around(a, decimals =  1))
print (np.around(a, decimals =  -1))

[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


### numpy.floor() & numpy.ceil()
两个函数分别向下或向上取整

In [28]:
a = np.array([-1.7,  1.5,  -0.2,  0.6,  10])
print(np.floor(a))
print()
print(np.ceil(a))

[-2.  1. -1.  0. 10.]

[-1.  2. -0.  1. 10.]


# 算术函数
算术函数包含简单的加减乘除: add()、subtract()、multiply()和divide()

In [30]:
a = np.arange(9, dtype = np.float_).reshape(3, 3)
print(a)
print()
b = np.array([10, 10, 10])
print(b)
print()
print(np.add(a, b))
print()
print(np.subtract(a, b))
print()
print(np.multiply(a, b))
print()
print(np.divide(a, b))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

[10 10 10]

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]

[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]

[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


### numpy.reciprocal
返回参数逐元素的倒数

In [31]:
a = np.array([0.25, 1.33, 1, 100])
print(a)
print(np.reciprocal(a))

[  0.25   1.33   1.   100.  ]
[4.        0.7518797 1.        0.01     ]


### numpy.power()
将第一和参数作为底数，计算它与第二个输入数组中相对应元素的幂

In [33]:
a = np.array([10, 100, 1000])
print(a)
print()
print(np.power(a, 2))
print()
b = np.array([1, 2, 3])
print(b)
print()
print(np.power(a, b))

[  10  100 1000]

[    100   10000 1000000]

[1 2 3]

[        10      10000 1000000000]


### numpy.mod() & numpy.remainder()
计算输入数组中相应元素的相处后的余数

In [34]:
a = np.array([10, 20, 30])
b = np.array([3, 5, 7])
print(a)
print()
print(b)
print()
print(np.mod(a, b))
print()
print(np.remainder(a, b))

[10 20 30]

[3 5 7]

[1 0 2]

[1 0 2]


# 统计函数
NumPy提供了很多统计函数，用于从数组中查找最小元素、最大元素、百分位标准差和方差等
## numpy.amin() & numpy.amax()
分别用于计算数组中的元素沿指定轴的最小值和最大值

In [51]:
a = np.array([[3, 7, 5],
                          [8, 4, 3],
                          [2, 4 ,9]])
print(np.amin(a, 1))
print(np.amin(a, 0))
print(np.amax(a))
print(np.amax(a, axis = 0))

[3 3 2]
[2 4 3]
9
[8 7 9]


## numpy.ptp()
计算数组中元素最大值与最小值的差

In [37]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print (np.ptp(a))
print (np.ptp(a, axis =  1))
print (np.ptp(a, axis =  0))

7
[4 5 7]
[6 3 6]


## numpy.percentile()
百分位数是统计中使用的度量，表示小于这个值的观察值百分比
```py
numpy.percentile(a, q, axis)
```
- q: 要计算的百分位数，在0~100之间
- axis: 沿着它计算百分位数的轴

In [39]:
a = np.array([[10, 7, 4], [3, 2, 1]])
print(a)

print(np.percentile(a, 50))
print()
print(np.percentile(a, 50, axis=0))
print()
print(np.percentile(a, 50 , axis=1))
print()
print(np.percentile(a, 50, axis=1, keepdims=True))

[[10  7  4]
 [ 3  2  1]]
3.5

[6.5 4.5 2.5]

[7. 2.]

[[7.]
 [2.]]


## numpy.median() & numpy.mean() & numpy.average()
分别计算数组的中位数、算术平均数和加权平均数

In [41]:
a = np.array([1, 2, 3, 4])
print(np.average(a))    #不指定权重时相当于算术平均数
wts = np.array([4, 3, 2, 1])
print(np.average(a, weights = wts))

2.5
2.0


## numpy.std() & numpy.var()
分别计算数组的标准差和方差

In [42]:
print(np.std([1, 2, 3, 4]))
print(np.var([1, 2, 3, 4]))

1.118033988749895
1.25


# 排序、条件刷选函数 
NumPy提供了多种排序的方法，这些排序函数实现不同的排序算法，每个排序算法的特征在于执行速度、最坏情况性能、所需工作空间和稳定性

下面显示了三种排序算法的比较

|种类|	速度|	最坏情况|	工作空间|	稳定性|
|:---:|:---:|:---:|:---:|:---:|
|'quicksort'（快速排序）|	1|	O(n^2)|	0|	否|
|'mergesort'（归并排序）	|2|	O(n*log(n))	|~n/2|	是|
|'heapsort'（堆排序）	|3|	O(n*log(n))|	0|	否|

## numpy.sort()
函数返回输入数组的排序副本
```python
numpy.sort(a, axis, kind, order)
```
- axis：沿着它排序数组的轴，如果不给定轴，数组会被展开；为0时按列排序，为1时按行排序
- kind：默认为'quicksort'（快速排序）
- order：如果数组包含字段，则是要排序的字段

In [54]:
a = np.array([[3, 7], [9, 1]])
print(a)
print()
print(np.sort(a))
print()
print(np.sort(a, axis=0))    #按列排序
print()
#在sort函数中排序字段
dt = np.dtype([('name', 'S10'), ('age', int)])

[[3 7]
 [9 1]]

[[3 7]
 [1 9]]

[[3 1]
 [9 7]]

