# 迭代数组
使用arange()函数创建一个 2  x 3 数组，并用nditer对它进行迭代

In [47]:
import numpy as np

In [48]:
a = np.arange(6).reshape(2, 3)
for x in np.nditer(a):
    print(x, end=', ')

0, 1, 2, 3, 4, 5, 

## 控制遍历顺序
- for x in np.nditer(a, order = 'F') : Fortran order      列序优先
- for x in np.nditer(a.T, order = 'C') : C order                行序优先

In [49]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组是")
print(a)
print()
b = a.T
print("原始数组的转置是")
print(b)
print()
c = b.copy(order = 'C')
print("以C风格排序")
print(c)
for x in np.nditer(c):
        print(x, end=', ')
print()
print()
d = b.copy(order = 'F')
print("以F风格排序")
print(d)
for x in np.nditer(d):
        print(x , end=', ')

原始数组是
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

原始数组的转置是
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

以C风格排序
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

以F风格排序
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

可以通过显式设置，来强制nditer对象使用某种顺序

In [50]:
a = np.arange(0, 60, 5).reshape(3, 4)
print("原始数组")
print(a)
print()
print("以C风格排序")
for x in np.nditer(a, order = 'C'):
    print (x, end = ', ')
print("\n")
print("以F风格排序")
for x in np.nditer(a, order = 'F'):
    print(x, end = ', ')

原始数组
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

以C风格排序
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

以F风格排序
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

## 修改数组中元素的值
nditer对象有另一个可选参数op_flags

默认情况下，nditer将待迭代遍历的数组视为只读对象，为了在遍历数组的同时，实现对数组元素值的修改，必须指定readwrite或者writeonly模式


In [51]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组是")
print(a)
print()
for x in np.nditer(a, op_flags = ['writeonly']):
        x[...] = 2 * x
print("修改后的数组为")
print(a)

原始数组是
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

修改后的数组为
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


## 使用外部循环
nditer类的构造器用于flags参数，它可以接受下列值

|参数|描述|
|:---:|:---|
|c_index|	可以跟踪 C 顺序的索引|
|f_index|	可以跟踪 Fortran 顺序的索引|
|multi_index|	每次迭代可以跟踪一种索引类型|
|external_loop|	给出的值是具有多个值的一维数组，而不是零维数组|

In [52]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("原始数组")
print(a)
print()
print("修改后的数组是")
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
    print(x, end='')

原始数组
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

修改后的数组是
[ 0 20 40][ 5 25 45][10 30 50][15 35 55]

## 广播迭代
如果两个数组是可广播的，nditer组合对象能够同时迭代它们

假设a的维度为 3 x 4， b的维度为 1 x 4， 则使用下列迭代器

In [53]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("第一个数组为")
print(a)
print()
b = np.array([1, 2, 3, 4], dtype = int)
print("第二个数组为")
print(b)
print()
print("修改后的数组为")
for x, y in np.nditer([a, b]):
    print("%d:%d" % (x, y), end = ', ')

第一个数组为
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

第二个数组为
[1 2 3 4]

修改后的数组为
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

# 数组操作
数组操作大概可以分为下面几类
- 修改数组形状
- 翻转数组
- 修改数组维度
- 连接数组
- 分割数组
- 数组元素的添加和删除

## 修改数组形状

|函数|描述|
|:---:|:---|
|reshape	|不改变数据的条件下修改形状|
|flat	|数组元素迭代器|
|flatten	|返回一份数组拷贝，对拷贝所做的修改不会影响原始数组|
|ravel	|返回展开数组|

### numpy.reshape
可以在不改变数据的情况下修改形状
```py
numpy.reshape(arr, newshape, order='C')
```
- order: 'C'按行， 'F'按列， 'A'原顺序，'K'元素在内存中出现的顺序

In [54]:
a = np.arange(8)
print(a)
print()

b = a.reshape(4, 2)
print(b)

[0 1 2 3 4 5 6 7]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### numpy.ndarray,flat
是一个数组元素迭代器

对数组中**每个元素**进行处理，可以使用flat属性

In [55]:
a = np.arange(9).reshape(3, 3)
for row in a:
    print(row)
print()    
for element in a.flat:
    print(element)

[0 1 2]
[3 4 5]
[6 7 8]

0
1
2
3
4
5
6
7
8


### numpy.ndarray.flatten
返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
```py
ndarray.flatten(order='C')
```

### numpr.ravel
展平的数组元素，顺序通常是C风格，返回的是数组视图，修改会影响原始数组
```py
numpy.ravel(a, order='C')
```

## 翻转数组

|函数|描述|
|:---:|:---|
|transpose|	对换数组的维度|
|ndarray.T|	和 self.transpose() 相同|
|rollaxis|	向后滚动指定的轴|
|swapaxes|	对换数组的两个轴|

### numpy.transpose
用于对换数组的维度
```py
numpy.transpose(arr, axes)
```
- axes为整形列表，对应维度，通常所有维度都会对换

In [56]:
a = np.arange(12).reshape(3, 4)
print(a)
print()
print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### numpy.ndarray.T
类似与numpy.transpose

In [57]:
print(a.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### numpy.rollaxis
向后滚动特定的轴到一个特定位置
```python
numpy.rollaxis(arr, axis, start)
```
- axis 向后滚动的轴，其他轴的相对位置不会改变
- start 默认为0，表示完整的滚动，否则会滚动到特定的位置

In [58]:
a = np.arange(8).reshape(2, 2, 2)
print("原数组")
print(a)
print("---------------------")

print(np.where(a == 6))
print(a[1, 1, 0])
print("----------------------")

b = np.rollaxis(a, 2, 0)  # 将轴2滚动到轴0 (宽度到深度)
print(b)
print(np.where(b == 6))
print("------------------------")

c = np.rollaxis(a, 2, 1)  # 将轴2滚动到轴1（宽度到高度）
print(c)
print(np.where(c == 6))

原数组
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
---------------------
(array([1]), array([1]), array([0]))
6
----------------------
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
(array([0]), array([1]), array([1]))
------------------------
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
(array([1]), array([0]), array([1]))


### numpy.swapaxes
详见np.rollaxis & swapaxes.ipynb

## 修改数组维度
|维度|	描述|
|:---:|:---|
|broadcast|	产生模仿广播的对象|
|broadcast_to|	将数组广播到新形状|
|expand_dims|	扩展数组的形状|
|squeeze|	从数组的形状中删除一维条目|

### numpy.broadcost
用于模仿广播的对象，返回一个对象，该对象封装了将一个数组广播到另一个数组的结果

In [59]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5 ,6])

# 对y广播x, 它具有iterator属性，基于自身组件的迭代器元组
b = np.broadcast(x, y)
r, c = b.iters

print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print("------------------------------")

print(b.shape) #shape返回广播对象的形状
print("------------------------------")

b = np.broadcast(x, y)
c = np.empty(b.shape)
print(c.shape)
print("==========")
c.flat= [u + v for (u, v) in b]
print(c)
print("=======")
print(x + y)

1 4
1 5
1 6
2 4
2 5
2 6
3 4
3 5
3 6
------------------------------
(3, 3)
------------------------------
(3, 3)
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


### numpy.broadcast_to
将数组广播到新形状。它在原始数组上只返回只读视图，它通常不连续

如果新形状不符合numpy的广播规则，则可能会抛出ValueError
```py
numpy.broadcast_to(arr, shape, subok)
```

In [60]:
a = np.arange(4).reshape(1, 4)
print(a)
print()
print(np.broadcast_to(a, (4, 4)))

[[0 1 2 3]]

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


### numpy.expand_dims
在指定位置插入新的轴来扩展数组的形状
```py
numpt.expand_dims(arr, axis)
```

In [61]:
x = np.array([[1, 2], [3, 4]])
print(x)
print()
y = np.expand_dims(x, axis=0)
print(y)
print()
print(x.shape, y.shape)
print("-----------------------------------")
y = np.expand_dims(x, axis=1)
print(y)
print()
print(x.ndim, y.ndim)
print(x.shape, y.shape)

[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]]

(2, 2) (1, 2, 2)
-----------------------------------
[[[1 2]]

 [[3 4]]]

2 3
(2, 2) (2, 1, 2)


### numpy.squeeze
从给定数组中删除一维的条目
```python
numpy.squeeze(arr, axis)
```

In [62]:
x = np.arange(9).reshape(1, 3, 3)
print(x)
print()
y = np.squeeze(x, axis=0)
print(y)
print()
print(x.shape, y.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

(1, 3, 3) (3, 3)


## 连接数组


|函数|	描述|
|:---:|:---|
|concatenate|	连接沿现有轴的数组序列|
|stack|	沿着新的轴加入一系列数组|
|hstack|	水平堆叠序列中的数组（列方向）|
|vstack|	竖直堆叠序列中的数组（行方向）|

### numpy.concatenate
用于沿指定轴连接形状相同的两个或多个数组
```py
nunpy.concatenate((a1, a2 ...), axis)
```
- axis很多地方都是默认为0

In [65]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print()
print(b)
print("-----------")
print(np.concatenate((a, b), axis=0))
print()
print(np.concatenate((a, b), axis=1))
print()

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]
-----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]



### numpy.stack
用于沿新轴连接数组序列
```py
numpy.stack(arrays, axis)
```

In [69]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.stack((a, b), 0))
print((np.stack((a, b), 0)).shape)
print()
print(np.stack((a, b), 1))
print((np.stack((a, b), 1)).shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


### numpy.hstack
是np.stack的变体，通过水平堆叠来生成数组

In [72]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print()
print(b)
print()
c = np.hstack((a, b))
print(c)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


### numpy.vstack
也是一种变体，通过垂直堆叠来生成数组

In [73]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 分割数组

|函数|	数组及操作|
|:---:|:---|
|split|	将一个数组分割为多个子数组|
|hsplit|	将一个数组水平分割为多个子数组（按列）|
|vsplit|	将一个数组垂直分割为多个子数组（按行）|

### numpy.split
沿特定轴将数组分割为子数组
```py
numpy.split(ary, indices_or_sections, axis)
```
- indices_or_sections: 如果是一个整数，就用该数平均分；如果是一个数组，为沿轴切分的位置（左开右闭）
- axis: 设置沿着哪个方向进行切分，默认为0，横向切分，即水平方向；为1时，纵向切分，即竖直方向

In [74]:
a = np.arange(9)
print(a)
print()
b = np.split(a, 3)
print(b)
print()
b = np.split(a, [4, 7])
print(b)

[0 1 2 3 4 5 6 7 8]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]
