## Ndarray 对象


In [35]:
import numpy as np


创建一个ndarray需要调用Numpy中的array函数
```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

| 名称 | 描述 |
| :---: | :--- |
| object | 数组或嵌套的数列 |
| dtype | 数组元素的数据类型，可选 |
| copy | 对象是否需要复制，可选 |
| order | 创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）|
| subok | 默认返回一个与基类类型一致的数组 |
| ndmin | 指定生成数组的最小维度 |

实例：

In [36]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [37]:
#最小维度
a = np.array([1, 2, 3, 4, 5], ndmin =  2)  
print (a)

[[1 2 3 4 5]]


In [38]:
# dtype 参数  
import numpy as np 
a = np.array([1,  2,  3], dtype = complex)  
print (a)

[1.+0.j 2.+0.j 3.+0.j]



## 数组属性

|属性|说明|
|:---:|:---|
|ndarray.ndim|	秩，即轴的数量或维度的数量|
|ndarray.shape|	数组的维度，对于矩阵，n 行 m 列|
|ndarray.size|	数组元素的总个数，相当于 .shape 中 n*m 的值|
|ndarray.dtype|	ndarray 对象的元素类型|
|ndarray.itemsize|	ndarray 对象中每个元素的大小，以字节为单位|
|ndarray.flags|	ndarray 对象的内存信息|
|ndarray.real|	ndarray元素的实部|
|ndarray.imag|	ndarray 元素的虚部|
|ndarray.data|	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性|

###  ndarray.ndim
用于返回数组的为数，等于秩

In [39]:
a = np.arange(24)              #np.arange()用于生成数组，与range()类似
print(a.ndim)                      #a现在只有一个维度
print(a)
print()
b = a.reshape(2, 4, 3)       #b现在拥有三个维度
print(b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### ndarray.shape
表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即ndim（秩）属性

In [40]:
a = np.array([[1, 2, 3], 
                           [4, 5, 6]])
print (a.shape)

(2, 3)


也可用于调整数组大小

In [41]:
a.shape = (3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


reshape()同样可以用于调整数组大小

In [42]:
a = np.array([[1, 2, 3], 
                           [4, 5, 6]])
print(a.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


- 区别：reshape()通常返回的是非拷贝副本，即改变返回后数组的元素，原数组对应元素的值也会改变

In [43]:
a = np.array([[1,2,3],
                          [4,5,6]])
print(a)
print()
b = a.reshape((6,))
print(b)
print()
b[0] = 99
print(b)
print()
print(a)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[99  2  3  4  5  6]

[[99  2  3]
 [ 4  5  6]]


### ndarray.itemsize
以字节的形式返回数组中**每一个元素**的大小

In [44]:
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1, 2, 3, 4, 5], dtype = np.int8)
print(x.itemsize) 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1, 2, 3, 4, 5], dtype = np.float64)
print(y.itemsize)

1
8


### ndarray.flags
详见[runoob](https://www.runoob.com/numpy/numpy-array-attributes.html)

## numpy创建数组


### numpy.empty
用于创建一个指定形状、数据类型且未初始化的数组
```python
numpy.empty(shape, dtype = float, order = 'C')
```
- order有两个可选项，'C'和'F'，分别代表行优先和列优先

In [45]:
x = np.empty([3, 2], dtype = int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


### numpy.zero/numpy.ones
与上面类似，数组元素用0/1来填充

In [46]:
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [47]:
# 默认为浮点数
x = np.ones(5) 
print(x)
 
# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


## 从已有的数组创建数组
### numpy.asarray
```python
numpy.asarray(a, dtype = None, order = None)
```
- a是任意形式的输入参数，可以是列表、元祖、多维数组等

In [48]:
x = [1, 2, 3]
a = np.asarray(x)
print(a)

y = (4, 5, 6)
b = np.asarray(y)
print(b)

a = np.asarray(x, dtype = float)
print(a)

[1 2 3]
[4 5 6]
[1. 2. 3.]


#### numpy.frombuffer
用于实现动态数组，接受buffer输入参数，以流的形式读入转换为ndarray对象
```python
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
```
- count为读取的数据数量，默认为-1，读取所有数据
- offset为读取的起始位置，默认为0

In [49]:
s = b'Hello, world'
a = np.frombuffer(s, dtype = 'S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b',' b' ' b'w' b'o' b'r' b'l' b'd']


### numpy.fromiter
可从迭代对象中建立ndarray对象，返回一维数组
```python
numpy.fromiter(iterable, dtype, count = -1)
```

In [50]:
list = range(5)
it = iter(list)

x = np.fromiter(it, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


## 从数值范围创建数组


### numpy.arange
```python
numpy.arange(start, stop, step, dtype)
```

In [51]:
x  = np.arange(5)
print(x)
y = np.arange(10, 20, 2)
print(y)

[0 1 2 3 4]
[10 12 14 16 18]


### numpy.linspace
用于创建一个一维数组，数组是一个**等差数列**构成的
```python
np.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)
```
|参数|	描述|
|:---:|:---|
|start	|序列的起始值|
|stop	|序列的终止值，如果endpoint为true，该值包含于数列中|
|num	|要生成的等步长的样本数量，默认为50|
|endpoint	|该值为 true 时，数列中包含stop值，反之不包含，默认是True|
|retstep	|如果为 True 时，生成的数组中会显示间距，反之不显示|
|dtype	|ndarray 的数据类型|

In [59]:
a = np.linspace(1, 10, 10)        # 第三个数字是要生成的样本量，不是步长
print(a)
a = np.linspace(1, 1, 10)
print(a)
a = np.linspace(10, 20, 5, endpoint = False)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10. 12. 14. 16. 18.]


### numpy.logspace
用于创建一个**等比数列**
```py
np.logspace(start, stop, num=50, endpoint = True, base=10.0, dtype=None)
```
|参数|描述|
|:---:|:---|
|start|	序列的起始值为：base ** start|
|stop|	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中|
|num|	要生成的等步长的样本数量，默认为50|
|endpoint|	该值为 true 时，数列中中包含stop值，反之不包含，默认是True|
|base|	对数 log 的底数|
|dtype|	ndarray 的数据类型|

In [61]:
a = np.logspace(1.0, 2.0, num=10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [62]:
a = np.logspace(0, 9, 10, base = 2)
print(a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


## 切片和索引
切片对象可以通过内置的slice函数，并设置start，stop和step参数进行，从原数组中切割出一个新数组

In [63]:
a = np.arange(10)
s = slice(2, 7, 2)
print(a[s])

[2 4 6]


也可以通过冒号分隔切片参数start:stop:step来进行切片操作

In [64]:
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [66]:
a = np.arange(10)
b = a[5]
c = a[2:]            #提取的元素不包括索引
d = a[2:5]
print(b)
print(c)
print(d)

5
[2 3 4 5 6 7 8 9]
[2 3 4]


多维数组同样适用上述提取方法

In [67]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a[1:])

[[3 4 5]
 [4 5 6]]


## 高级索引
除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引

In [68]:
x = np.array([[1, 2], 
                           [3, 4], 
                           [5, 6]])    
y = x[[0, 1, 2], [0, 1, 0]]    #整数数组索引，获取数组中 (0,0)，(1,1) 和 (2,0) 位置处的元素
print(y)

[1 4 5]


In [73]:
x = np.array([[0, 1, 2],
                            [3, 4, 5],
                            [6, 7, 8],
                            [9, 10, 11]])
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
print(rows)
print()
print(cols)
print()
y = x[rows, cols]        #获取 4X3 数组中的四个角的元素
print(y)

[[0 0]
 [3 3]]

[[0 2]
 [0 2]]

[[ 0  2]
 [ 9 11]]
