# 位运算
[runoob](https://www.runoob.com/numpy/numpy-binary-operators.html)


# 字符串函数
以下函数对dtype为numpy.string_或numpy.unicode_的数组执行向量化字符串操作

这些函数在字符数组类（numpy.char）中定义

|函数|	描述|
|:---:|:---|
|add()|	对两个数组的逐个字符串元素进行**连接**|
|multiply()|	返回按元素**多重连接**后的字符串|
|center()|	**居中**字符串|
|capitalize()|	将字符串第一个字母转换为大写|
|title()|	将字符串的每个单词的第一个字母转换为大写|
|lower()|	数组元素转换为小写|
|upper()|	数组元素转换为大写|
|split()|	指定分隔符对字符串进行**分割**，并返回数组列表|
|splitlines()|	返回元素中的行列表，以换行符**分割**|
|strip()|	**移除**元素开头或者结尾处的特定字符|
|join()|	通过指定分隔符来**连接**数组中的元素|
|replace()|	使用新字符串**替换**字符串中的所有子字符串|
|decode()|	数组元素依次调用str.decode|
|encode()|	数组元素依次调用str.encode|

In [16]:
import numpy as np
print("使用add()连接两个字符串：")
print(np.char.add(['Hello, '], ['World!']))
print(np.char.add(['Hello ', 'Hi '], ['abc', 'xyz']))
print()

print("使用multiply()进行多重连接：")
print(np.char.multiply('HelloWorld', 3))
print()

print("使用center()使字符串居中：")
print(np.char.center('HelloWorld', 20, fillchar='#'))
print()

print("使用capitalize()将字符串的第一个字母转换为大写：")
print(np.char.capitalize('hello'))
print()

print("使用title()将每个单词的首字母大写：")
print(np.char.title('hello world'))
print()

print("使用lower()、upper()对所有字母大小写：")
print(np.char.lower('HELLO'))
print(np.char.upper('world'))
print()

print("使用splitlines()以换行符为分隔来分隔字符串，并返回数组：")
print("\\n，\\r，\\r\\n 都可用作换行符")
print(np.char.splitlines('I love \n the world'))
print(np.char.splitlines('I love \r the world'))

使用add()连接两个字符串：
['Hello, World!']
['Hello abc' 'Hi xyz']

使用multiply()进行多重连接：
HelloWorldHelloWorldHelloWorld

使用center()使字符串居中：
#####HelloWorld#####

使用capitalize()将字符串的第一个字母转换为大写：
Hello

使用title()将每个单词的首字母大写：
Hello World

使用lower()、upper()对所有字母大小写：
hello
WORLD

使用splitlines()以换行符为分隔来分隔字符串，并返回数组：
\n，\r，\r\n 都可用作换行符
['I love ', ' the world']
['I love ', ' the world']


In [22]:
print("strip()用于移除开头或结尾处的特定字符: ")
print(np.char.strip('Jupyter Notebook', 'Ju'))
print(np.char.strip('Jupyter  Notebok', 'ok'))
print()

print("join()通过分隔符来连接数组元素中的元素或字符串：")
print(np.char.join(' : ', 'HELLO'))
print(np.char.join([' : ', ' - '], ['google', 'brain']))
print()

print("replace()使用新字符串替换字符串中所有子字符串：")
print(np.char.replace('Hello world', 'or', 'cc'))
print()

print("encode()对数组中每个元素调用str,encode函数，默认编码是 utf-8，可以使用标准 Python 库中的编解码器")
a = np.char.encode('runoob', 'cp500') 
print (a)
print()

print("decode() 函数对编码的元素进行 str.decode() 解码")
a = np.char.encode('runoob', 'cp500') 
print (a)
print (np.char.decode(a,'cp500'))

strip()用于移除开头或结尾处的特定字符: 
pyter Notebook
Jupyter  Noteb

join()通过分隔符来连接数组元素中的元素或字符串：
H : E : L : L : O
['g : o : o : g : l : e' 'b - r - a - i - n']

replace()使用新字符串替换字符串中所有子字符串：
Hello wccld

encode()对数组中每个元素调用str,encode函数，默认编码是 utf-8，可以使用标准 Python 库中的编解码器
b'\x99\xa4\x95\x96\x96\x82'

decode() 函数对编码的元素进行 str.decode() 解码
b'\x99\xa4\x95\x96\x96\x82'
runoob


# 数学函数
NumPy包含大量的各种数学运算的函数，包括三角函数、算术运算的函数及复数处理函数等

## 三角函数
sin()、cos()和tan()

arcsin()、arccos()和arctan()

numpy.degrees() 函数可以将弧度转换为角度

In [24]:
a = np.array([0, 30, 45, 60, 90])
print(np.sin(a * np.pi / 180))
print()
print(np.cos(a * np.pi / 180))
print()
print(np.tan(a * np.pi / 180))

[0.         0.5        0.70710678 0.8660254  1.        ]

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


## 舍入函数
numpy.around()返回指定数字的四舍五入值
```py
numpy.around(a, decimals)
```
- decimals：舍入的小数位数，默认为0；如果为负数，整数将四舍五入到小数点左侧的位置

In [26]:
a = np.array([1.0, 5.55, 123, 0.567, 25.532])
print(np.around(a))
print (np.around(a, decimals =  1))
print (np.around(a, decimals =  -1))

[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]
